### ISSUE TITLE
Question about the COCO experiments

### ISSUE THREAD

**Issue by HaisongDing** [Katie0723/DQ-DETR#3]
In your paper, DQ-DETR yieldes slightly lower performance compared with DINO. My followup questions are:
1. Is the degradation caused by the "Dynamic Query Selection (DQS)" part?
2. Have you tried applying "Categorical Counting (CC)" and "Feature Enhancement (FE)" designs only and checked whether it will achieve better results than DINO?

**Comment by hoiliu-0801** [comment]
1. Our paper focuses on tiny object detection, with components specifically designed for this task. Achieving state-of-the-art performance across all datasets is challenging. In contrast, DQ-DETR outperforms DINO significantly in tiny object datasets. 
2. Thank you for the suggestion. We are still working on it.
